### ISSUE TITLE
Running the config script in Microsoft Tanent And cannot work

### ISSUE THREAD

**Issue by adashen** [Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ X] documentation issue or request
```

### Minimal steps to reproduce
> Follow the steps to execute the configure.ps1. 
> GetRequiredPermissions will fail since there will be several SPs for the same application name
> I got fixed issue to use application ID and finally the script running successfully
> Now run the app.
> After sign in and consent the permission. Got message box
![image](https://user-images.githubusercontent.com/1872137/74516747-e7e66900-4f4b-11ea-96e9-414be38e5d6e.png)

I am in the microsoft tanent.

**Comment by TiagoBrenck** [comment]
Did you run `Cleanup.ps1` before?

**Comment by adashen** [comment]
I have cleaned the apps before running the script. The issue here is although the apps are created, but during running I still got the above information "need admin approval". So what configuration is missing? I am from microsoft and using Microsoft tenant.

**Comment by TiagoBrenck** [comment]
Are you registering it in the China portal, or global portal?

**Comment by adashen** [comment]
@TiagoBrenck, I use global poral.

**Comment by TiagoBrenck** [comment]
As far as I know, you cannot use Microsoft tenant to create the applications since our users don't have permissions for that operation. @kalyankrishna1 can you confirm?

**Comment by kalyankrishna1** [comment]
yes, you need to get a special approval from the MSFT corp admin. Search the internal SO for guidance.
