### ISSUE TITLE
Issue on manual setup

### ISSUE THREAD

**Issue by Illeris** [Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Manually follow the steps for creating the applications in azure ad (through portal.azure.com)

### Any log messages given by the failure
>Login fails with 401 error

### Expected/desired behavior
> Login should work

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Compared manual result with auto created one through PS1 scripts. These made things fail:
- ps1 script sets defaults (in manifest, for service app)
"accessTokenAcceptedVersion": null,
"signInAudience": "AzureADMultipleOrgs",

Works. However, manual creation defaults accessTokenAcceptedVersion to 2, and enables using personal accounts. However, when doing this, there is no way to get the todolist items from the SPA or service client. Always returns 401. 
When changing the default (auto created by ps1 script) to switch to 
accessTokenAcceptedVersion: 2,
"signInAudience": "AzureADandPersonalMicrosoftAccount"
The retrieve fails with 401 (login works, fetching data not)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by adashen** [comment]
Same issue here, after login I got "unauthorized" error in the sample  client.

**Comment by TiagoBrenck** [comment]
I will take a look.

**Comment by TiagoBrenck** [comment]
Please, refer to [this sample](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/3.-Web-api-call-Microsoft-graph-for-personal-accounts) to use MSA
