### ISSUE TITLE
update sample to use the Microsoft.Identity.Web.TokenCache.

### ISSUE THREAD

**Issue by gladjohn** [Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#42]
Thanks @GladwinJohnson 

We also have an opportunity, in this sample to change the token cache serialization (which is custom) to use the Microsoft.Identity.Web.TokenCache.

_Originally posted by @jmprieur in https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof/pull/41#pullrequestreview-785129802_

**Comment by jmprieur** [comment]
@aremo-ms is it something you could do?
This sample needs to be cleaned-up to remove all the code that is provided by Microsoft.Identity.Web

**Comment by aremo-ms** [comment]
I've merged the appropriate [PR](https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof/pull/44) and closing this issue for now
