### ISSUE TITLE
Update to use AAD v2.0 endpoint

### ISSUE THREAD

**Issue by kalyankrishna1** [Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#49]
> Please provide us with the following information:
> ---------------------------------------------------------------
We have enough code and info to use AAD v2.0 endpoint in TodoList service, so let's not advise usage of older endpoint
 
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aremo-ms** [comment]
Hi @bgavrilMS 
maybe you will be able to advise here. I'm trying to switch to Token v2.0
For that reason I've set a Service Manifest value to "accessTokenAcceptedVersion": 2
Then the call to todo list is unauthorized.
Any thoughts?

Thanks
Alex

**Comment by Amondale** [comment]
Anybody know the strlen() of the longest .Net module? This could be close to the "Blue Ribbon:" WindowsAzureActiveDirectoryBearerAuthenticationOptions == 51 bytes.

**Comment by bgavrilMS** [comment]
@Amondale - https://twitter.com/codinghorror/status/506010907021828096?lang=en-GB

**Comment by aremo-ms** [comment]
the issue is resolved
